apiVersion: lyra.example.com/v1alpha1
kind: Workflow
metadata:
  name: sample2-workflow
spec:
  workflowName: "sample2"
  data:
    aws.tags.created-by: user@company.com
    aws.tags.lifetime: 3hr
  refreshTime: 10
