apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: webservers.lyra.example.com
spec:
  group: lyra.example.com
  names:
    kind: WebServer
    listKind: WebServerList
    plural: webservers
    singular: webserver
    shortNames:
    - ws
  scope: Namespaced
  version: v1alpha1
  subresources:
    status: {}
  additionalPrinterColumns:
      - name: WebServerName
        type: string
        description: The name of the webserver
        JSONPath: .spec.loadBalancerName
      - name: WebServerId
        type: string
        description: The ID of the web server
        JSONPath: .spec.webServerId
